// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcyelkxzrzhegxssvldl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjeWVsa3h6cnpoZWd4c3N2bGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MDQ0OTgsImV4cCI6MjA1MjQ4MDQ5OH0.9NasknO8wZjHAvrBpRVmnnLgur4V_qgxp0p2wn1HOjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);